export const MAX_CUSTOMER_APP_SERVICE_IDS = 10;
export const MAX_CUSTOMER_BOOKING_NOTES_LENGTH = 500;
export const DEFAULT_CUSTOMER_APP_BOOKINGS_LIMIT = 50;
export const MAX_CUSTOMER_APP_BOOKINGS_LIMIT = 100;
